@geo_api_HostAddress = https://localhost:7079/

GET https://localhost:7079/api/shipment

###

GET https://localhost:7079/api/shipment/near

### 

POST https://localhost:7079/api/shipment/seed


###
POST https://localhost:7079/api/shipment
Content-Type : application/JSON


{
  "trackingNumber": "TRK-1112",
  "metaData": {
    "customerId": "C212",
    "customerName": "Mahual Sharma",
    "shippingAddress": "Sector -18, rohini, Delhi",
    "Productname": "Laptop Bag",
    "Category": "Accessories",
    "Price": 75000,
    "IsFragile": false,
    "status": "Delay"
  },
  "currentLoc": {
    "longitude": 77.010,
    "latitude": 29.595
  }
}

###

DELETE https://localhost:7079/api/shipment/69e8b46a293651f1b6952058

###

POST https://localhost:7079/api/shipment/location/by-id?id=69e88499ff4d1ec1d50ad5bc
Content-Type : application/JSON

{
  "longitude": -74.0404,
  "latitude": 40.6780
}

###
POST https://localhost:7079/api/shipment/location/by-track?trackNum=TRK1004
Content-Type : application/JSON

{
  "longitude": -73.9968,
  "latitude": 42.9208
}

###

GET https://localhost:7079/api/shipment/by-distance?lon=-74.0060&lat=40.7128

###
GET https://localhost:7079/api/shipment/speeding-alerts?speedLimit=60

###
